Firmware
ut-robotics/picr22-team-teletupsud pull request #59
Opened 2022-12-27 20:46 UTC by MedvedEE

Mainboard firmware works

2023-01-02 18:54 UTC, ReikoR requested changes
Some minor problems.

2023-01-02 18:54 UTC, ReikoR commented on .gitignore
> +.gitignore
`t` is probably incorrect here and `.gitignore` should not be ignored.

2023-01-02 18:54 UTC, ReikoR commented on firmware/USB_Device/App/usbd_cdc_if.h
> + void CDC_On_Receive(uint8_t* buffer, uint32_t* length); // (1)
A bit more correct place for this function declaration would be at the end of the file between these lines:
```
/* USER CODE BEGIN EXPORTED_FUNCTIONS */

/* USER CODE END EXPORTED_FUNCTIONS */
```

2023-01-03 17:11 UTC, MedvedEE commented
Fixed

2023-01-03 17:40 UTC, ReikoR approved these changes

2023-01-03 20:59 UTC, merged